[project]
name = "mcp-server-saillogger"
version = "0.1.0"
description = "Saillogger MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
